apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: goslang-deployment
  labels:
    app: goslang-deployment
spec:

  replicas: 1
  template:
    metadata:
      labels:
        app: goslang
    spec:
      volumes:
      - name: shared-data
        emptyDir: {}
      containers:
      - name: goslang-backend
        image: scko823/goslang:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: shared-data
          mountPath: /app/assets

      - name: goslang-ui
        image: scko823/goslang-ui:1.0.0
        volumeMounts:
        - name: shared-data
          mountPath: /pod-data
        command: ["/bin/sh"]
        args: ["-c", "cp -r /usr/src/app/assets/* /pod-data && while true; do sleep 5; done"]
